### ISSUE TITLE
Create official documents how to deploy the latest code base to netlify. 

### ISSUE THREAD

**Issue by GochaLearningSpace** [Willings-Inc/SCG#196]

**Comment by GochaLearningSpace** [comment]
@amanscisingh  can you confirm this message ?

**Comment by amanscisingh** [comment]
@GochaLearningSpace The following are the steps for that...

PART 1 | Creating the build files in terminal
1. Open codebase and make sure you have the latest code
2. run `npm run build` in the terminal
3. This command after it's successful execution will generate build files in a folder named 'www'
4. you need to upload this folder manually to Netlify in order to deploy it to production

PART 2 | Accessing netlify account and deploying latest code there

1. Login to the Netlify account using the following credentials 
    saswatiisabella2002@gmail.com
    QOHS_PROD1234

6. Go to Sites and then choose the project named 'qohs-prod'
7. Then Go to Deploys section and scroll the page to the bottom, there you will find a 'browse files to upload' section, you can select the 'www' folder that you generated by `npm run build` here 
8. After that the latest code will be deployed live within seconds

**Comment by GochaLearningSpace** [comment]
> @GochaLearningSpace The following are the steps for that...
> 
> PART 1 | Creating the build files in terminal
> 
> 1. Open codebase and make sure you have the latest code
> 2. run `npm run build` in the terminal
> 3. This command after it's successful execution will generate build files in a folder named 'www'
> 4. you need to upload this folder manually to Netlify in order to deploy it to production
> 
> PART 2 | Accessing netlify account and deploying latest code there
> 
> 1. Login to the Netlify account using the following credentials
>    [saswatiisabella2002@gmail.com](mailto:saswatiisabella2002@gmail.com)
>    QOHS_PROD1234
> 2. Go to Sites and then choose the project named 'qohs-prod'
> 3. Then Go to Deploys section and scroll the page to the bottom, there you will find a 'browse files to upload' section, you can select the 'www' folder that you generated by `npm run build` here
> 4. After that the latest code will be deployed live within seconds

@amanscisingh 
Thank you.

@ShivomA @NimbleNitesh 
Can you confirm whether above steps work for you  ?

**Comment by NimbleNitesh** [comment]
Thank you for sharing the steps, @amanscisingh @GochaLearningSpace ! I followed the instructions and successfully completed the deployment process.

**Comment by GochaLearningSpace** [comment]
@NimbleNitesh ok good news, can you share the link you succeeded to deploy, let's test it out.

**Comment by NimbleNitesh** [comment]
This is from my Netlify Id:
https://649ec066c3bf55009c55112a--effervescent-klepon-408563.netlify.app/
I have also added the code with the message to be shown in Issue #195.Could you please verify it? When I tested the site from my browser, the message appeared fine to me.
![image](https://github.com/Willings-Inc/SCG/assets/76262941/3a1380b7-f9a8-4da0-a23d-22cf0cf65407)
